namespace images.alg1jogo {
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const agua = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const anel_agua_marinha = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const anel_pedra_solar = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const arco = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const ASAS = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const bardo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const bau_dourado = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const bau_dourado_aberto = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const bau_madeira = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const bau_velho = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const buraco = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const cadeado_dourado = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const cerca_madeira = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const chave_dourada = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const chave_prata = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const coracao = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const dragao = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const dullahan = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const elfo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const escudo_redondo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const espada = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const espinhos = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const esqueleto = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const fantasma = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const flecha = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const frango_assado = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const goblin = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const gosma_azul = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const gosma_verde = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const macaco = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const mago = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const martelo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const parede = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const parede_buracos = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const parede_espinhos = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const pato = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const pilar = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const portao_ferro = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const porta_madeira = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const porta_madeira_cadeado_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const porta_madeira_cadeado_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    //% tags="alg1jogo"
    export const soldado = image.ofBuffer(hex``);
}
